### ISSUE TITLE
installed but there are problems

### ISSUE THREAD

**Issue by piretro999** [CarstenAgerskov/skill-the-cows-lists#1]
HI, I did the manual installation and the anthentication and token get action work fine.
I then tried to "add milk to my grocery list" using the CLI console but here is the error it returned

09:32:14.669 - skill-the-cows-lists-master__init__ - ERROR - Error: u'errorMessage'
09:32:14.678 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "TheCowsLists.add_item_to_list_intent"}, "context": null}

I maybe forgot something...

**Comment by piretro999** [comment]
And now, magically, it works. Just remember to ad the list "grocery" to the remember the milk site

**Comment by jonubulin** [comment]
I am facing the same issue. I created a "grocery" list but I am still getting an error message:

`10:17:31.430 - SKILLS - DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-us", "utterances": ["add milk to my grocery list"]}, "context": null}
10:17:31.439 - SKILLS - DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": 1371329651, "utterances": ["add milk to my grocery list"]}, "context": null}
10:17:31.458 - SKILLS - DEBUG - {"type": "skill.converse.response", "data": {"skill_id": 1371329651, "result": false}, "context": null}
10:17:31.559 - SKILLS - DEBUG - {"type": "1371329651:AddItemToListIntent", "data": {"listName": "grocery", "confidence": 0.25, "target": null, "itemName": "milk", "intent_type": "1371329651:AddItemToListIntent", "AddItemToList": "add"~~~~
10:17:31.572 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "TheCowsLists.add_item_to_list_intent"}, "context": null}
10:17:31.931 - skill-the-cows-lists__init__ - ERROR - Error: u'errorMessage'
10:17:31.939 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "TheCowsLists.add_item_to_list_intent"}, "context": null}
`

**Comment by CarstenAgerskov** [comment]
Hi @jonubulin
Are you able to add items to one of the default lists, like "Inbox"?
Does Mycroft answer when you try to add to the grocery list? And if so, what does it say?
When you authenticated, did Mycroft end up saying "I got a token. I am now ready to put items on your lists. Ask me to add something to my Inbox list"?

**Comment by CarstenAgerskov** [comment]
I was able to reproduce the problem. A bug fix is on the way.

The problem may arise, if authentication failed, or was not performed. Or the skill may not have realized that a valid token is available.

Work around that may solve the problem:

The authentication was successful if Mycroft said "I got a token. I am now ready to put items on your lists. Ask me to add something to my Inbox list". If this did not happen, follow the steps in the "Configuration" section in [README.md](https://github.com/CarstenAgerskov/skill-the-cows-lists#readme).

If is still does not work after successful authentication, the skill may have to be reloaded, for the skill to realize that a valid token is present. (This should only happen if settings.json was updated manually, or by another running instance of the skill). Either restart Mycroft, or logon to the Mycroft server and `touch /opt/mycroft/skills/skill-the-cows-lists/__init__.py`

**Comment by jonubulin** [comment]
It is working now, thanks for your quick response. I have a short question however. When saying "add remember to call home tomorrow at 9 to list Inbox" shouldn't this create a time event at 9? Currently this creates only a task called "add remember to call home tomorrow at 9 to list Inbox" If this is not the right place to ask this question, I can create a separate issue.

**Comment by CarstenAgerskov** [comment]
@jonubulin 
You are right. and copy/paste of "add remember to call home tomorrow at 9 to list Inbox" into Mycrofts cli actually does that for me. Mycroft will just repeat your request, but in RTM a due date should be set.
You may try to see how Mycroft translate your request to text in the cli, or you may try to add the event directly in RTM (old fashioned writing:) ) like "remember to call home tomorrow at 9", just to see if is works there. 
If it still fails, please open another issue.
