### ISSUE TITLE
'Skill' in skill title

### ISSUE THREAD

**Issue by krisgesling** [CarstenAgerskov/skill-the-cows-lists#17]
Hi Carsten,

This is not an "issue" so much as a little housekeeping we are doing for the [Marketplace](https://market.mycroft.ai/). We are asking Skill Developers to consider removing the word "skill" from the title of all skills in your readme. 

The intention is to provide a more consistent experience as users explore the Skills available, and when Skills are verbally suggested through the device itself. 

If you are happy to do so, it would be great if you could just delete the word 'skill' from the main title of the readme. No need to update anything else. If you then resubmit the Skill using `mycroft-msk upgrade` we will be able to merge it quickly as there are no code or functionality changes.

Thanks
Gez

**Comment by CarstenAgerskov** [comment]
Hi Gez

The README was updated, and the PR has been submitted.

Regards Carsten
