### ISSUE TITLE
Clarification 

### ISSUE THREAD

**Issue by Nate-mycroft** [CarstenAgerskov/skill-the-cows-lists#4]
I was searching for this, so thank you very much for making this skill.

One thing to note was that I went into RtM, and put in a list called Grocery List.   When I tried your example of, Hey Mycroft, Add Milk to the Grocery List, I received an error.   After a few times of playing with it, I realized that "List" in my RtM app was the issue.   So I deleted the List in Grocery and it worked great.  Do you think there is anyway, other than updating the readme to make it so others don't do the same thing?  Or so that you can say it either way.

Thanks again.  Great instructions and skill.

**Comment by CarstenAgerskov** [comment]
Thanks for the feedback, great that you like it.
You are right, using the word "list" in a list name confuses the skill. I also experience a few other oddities with the parsing.
For the next release I will update the readme. I will consider a solution for this issue, but the main priorities are "undo" and "remove item" :)
