### ISSUE TITLE
Impossible to add task

### ISSUE THREAD

**Issue by Mermessus** [CarstenAgerskov/skill-the-cows-lists#5]
Hi, 
I have just installed the Cows lists on my picroft (with everything updated).
Everything went fine but even if Mycroft said that he was ready to add tasks I get this error when I try to add one:
`Error in add task to list intent at line 324`

Thanks for your help

**Comment by CarstenAgerskov** [comment]
Hi Mermessus

Thanks for reporting this.
From your description, I can see that the cows list does communicate with remember the milk. But it fails when trying to get all the lists. At this point in the code, it is the first time the cows lists depends on other software. If you installed by asking Mycroft verbally, or by using the msm command, the dependancies should have been installed. But it you installed for instance by copying the code, that could be the problem.

Another possibility is that your lists looks different from what the cows lists expect. Does the names of your lists contain special characters, non english characters perhaps? I dont think this will make the code fail, but I just didn't test it.
Do you have a pro account or the free account with remember the milk? I do my testing on the free account.


Unfortunately I can't reproduce the problem. It you are comfortable with using the command line, it will be of great help if you could take a look at the log: Logon to you mycroft and start the cli:
picroft: mycroft-cli-client
ubuntu or other, cd to your mycroft-core folder, then: ./start-mycroft.sh cli

You should see the log scrolling by, using up/down arrow keys or page up/down you can navigate the menu. You may want to resize the window horizontally to a larger size, to see more characters.

Try to add an item to a list, scroll to the end of the log. The error message should be visible. If you could copy and send it to me.

**Comment by CarstenAgerskov** [comment]
Hi Mermessus

I just pushed a new update to the cows lists. This version has a feature that will collect information about errors and send them to you upon request. In case of an error, the cows lists will ask you if you want a mail with the details. Answer yes, and forward the details to me.
With this function you don't need to go through the log as suggested above.

**Comment by Mermessus** [comment]
Hi, 

It seems it was a matter of langage. I put my RTM account in English and now everything works fine...
Thanks for the help.

**Comment by CarstenAgerskov** [comment]
Great, thanks for the feedback. I will put a note about language in the README file.
