### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by joshua-montgomery** [CarstenAgerskov/skill-the-cows-lists#6]
Using phrase "add watermelon to the shopping list" does not work.

Using phrase "add watermelon to my shopping list does"

Can you please tweak the syntax to allow the word "the" in place of "my"?

**Comment by CarstenAgerskov** [comment]
Consider it done:)
I appreciate you input, English is not my first language, i may not catch what the most natural phrase is for interacting with Mycroft.
