### ISSUE TITLE
Error when authenticating

### ISSUE THREAD

**Issue by tanglebridge** [CarstenAgerskov/skill-the-cows-lists#7]
Hi there. Just getting going with mycroft so I don't feel confident to fix this. Running on Ubuntu. I get the error message below. This seems like an API compatibility issue? I am using the dev branch - I assume that is the principal issue. Just thought I'd let you know.

`11:21:16.124 - __main__:handle_wakeword:57 - INFO - Wakeword Detected: hey mycroft
11:21:17.575 - __main__:handle_utterance:62 - INFO - Utterance: [u'authenticate with remember the milk']
~~~~roft.skills.core:wrapper:607 - ERROR - An error occurred while processing a request in The Cows Lists
Traceback (most recent call last):
File "/home/willem/src/mycroft-core/mycroft/skills/core.py", line 598, in wrapper
handler(message)
File "/home/willem/src/mycroft-core/mycroft/skills/context.py", line 43, in func_wrapper
ret = func(*args, **kwargs)
File "/home/willem/src/mycroft-core/mycroft/skills/context.py", line 43, in func_wrapper
ret = func(*args, **kwargs)
TypeError: authenticate_intent() takes exactly 1 argument (2 given)
`

**Comment by CarstenAgerskov** [comment]
Thanks for finding that problem. 
It should be corrected now, a new version is being pushed to your device soon. Or you can force an update now by restarting Mycroft.
